//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdgeWorks.PropertyCard.UI {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EdgeWorks.PropertyCard.UI.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PropertyCard Page Builder 的本地化字符串。
        /// </summary>
        public static string CardPageBuilder {
            get {
                return ResourceManager.GetString("CardPageBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YesOrNo 的本地化字符串。
        /// </summary>
        public static string CheckBoxName {
            get {
                return ResourceManager.GetString("CheckBoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Now... 的本地化字符串。
        /// </summary>
        public static string GenerateNow {
            get {
                return ResourceManager.GetString("GenerateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GroupBox 的本地化字符串。
        /// </summary>
        public static string GroupBoxName {
            get {
                return ResourceManager.GetString("GroupBoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More Properties 的本地化字符串。
        /// </summary>
        public static string MoreProperties {
            get {
                return ResourceManager.GetString("MoreProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create a new page template 的本地化字符串。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A property page for part files was not found.Click &apos;Create now...&apos; to launch the Property Tab Builder.  If you already have a template, place it in the folder specified in Property Settings folder. Click refresh button to refresh the page. 的本地化字符串。
        /// </summary>
        public static string NoTemplateNow {
            get {
                return ResourceManager.GetString("NoTemplateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NumberBox 的本地化字符串。
        /// </summary>
        public static string NumberBox {
            get {
                return ResourceManager.GetString("NumberBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open a file to view its properties 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open document to  view properties 的本地化字符串。
        /// </summary>
        public static string OpenFileToSeeProperty {
            get {
                return ResourceManager.GetString("OpenFileToSeeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as current template 的本地化字符串。
        /// </summary>
        public static string Save_As {
            get {
                return ResourceManager.GetString("Save As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TextBox 的本地化字符串。
        /// </summary>
        public static string TextBoxName {
            get {
                return ResourceManager.GetString("TextBoxName", resourceCulture);
            }
        }
    }
}
